// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShahBuyerFeaturesApi.Infrastructure.Contexts;

#nullable disable

namespace ShahBuyerFeaturesApi.Infrastructure.Migrations
{
    [DbContext(typeof(ShahDbContext))]
    partial class ShahDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.Address", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("BuyerProfileId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StoreInfoId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("WarehouseId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.AdminProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("AdminProfiles");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.BlacklistedToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BlacklistedTokens");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.BuyerProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("AddressId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageProfile")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("AddressId")
                        .IsUnique()
                        .HasFilter("[AddressId] IS NOT NULL");

                    b.ToTable("BuyerProfiles");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.CartItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("BuyerProfileId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ProductVariantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuyerProfileId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ParentCategoryId")
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.CountryCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CountryCodes");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.Favorite", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("BuyerProfileId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ProductVariantId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("BuyerProfileId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("BuyerProfileId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderPaymentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiptId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WarehouseOrderId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BuyerProfileId");

                    b.HasIndex("ReceiptId")
                        .IsUnique()
                        .HasFilter("[ReceiptId] IS NOT NULL");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.OrderItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ProductVariantId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.OrderPayment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("BuyerProfileId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GatewayTransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<decimal?>("RefundAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RefundReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BuyerProfileId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("OrderPayments");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("StoreInfoId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StoreInfoId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.ProductAttribute", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductAttributes");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.ProductAttributeValue", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ProductAttributeId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductAttributeId");

                    b.ToTable("ProductAttributeValues");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.ProductVariant", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeightInGrams")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVariants");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.ProductVariantAttributeValue", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ProductAttributeValueId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ProductVariantId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProductAttributeValueId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("ProductVariantAttributeValues");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.ProductVariantImage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<string>("ProductVariantId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("ProductVariantImages");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.Receipt", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("File")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.Review", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("BuyerProfileId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("Images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductVariantId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuyerProfileId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.SellerProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Passport")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("SellerTaxInfoId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("StoreInfoId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("SellerProfiles");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.SellerTaxInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("SellerProfileId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("TaxId")
                        .HasColumnType("int");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SellerProfileId")
                        .IsUnique()
                        .HasFilter("[SellerProfileId] IS NOT NULL");

                    b.HasIndex("TaxId");

                    b.ToTable("SellerTaxInfos");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.StoreInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("AddressId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CategoryId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("SellerProfileId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("StoreDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StoreEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StoreLogo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StorePhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique()
                        .HasFilter("[AddressId] IS NOT NULL");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SellerProfileId")
                        .IsUnique();

                    b.ToTable("StoreInfos");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.Tax", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RegexPattern")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Taxes");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("AdminProfileId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerProfileId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryCitizenshipId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SellerProfileId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CountryCitizenshipId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.Warehouse", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("AddressId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique()
                        .HasFilter("[AddressId] IS NOT NULL");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.WarehouseOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime?>("ShippedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WarehouseId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("WarehouseId");

                    b.ToTable("WarehouseOrders");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.Address", b =>
                {
                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.CountryCode", "Country")
                        .WithMany("Addresses")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.AdminProfile", b =>
                {
                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.User", "User")
                        .WithOne("AdminProfile")
                        .HasForeignKey("ShahBuyerFeaturesApi.Core.Models.AdminProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.BuyerProfile", b =>
                {
                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.Address", "Address")
                        .WithOne("BuyerProfile")
                        .HasForeignKey("ShahBuyerFeaturesApi.Core.Models.BuyerProfile", "AddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.User", "User")
                        .WithOne("BuyerProfile")
                        .HasForeignKey("ShahBuyerFeaturesApi.Core.Models.BuyerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.CartItem", b =>
                {
                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.BuyerProfile", "BuyerProfile")
                        .WithMany("CartItems")
                        .HasForeignKey("BuyerProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.ProductVariant", "ProductVariant")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BuyerProfile");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.Category", b =>
                {
                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.Favorite", b =>
                {
                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.BuyerProfile", "BuyerProfile")
                        .WithMany("Favorites")
                        .HasForeignKey("BuyerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.ProductVariant", "ProductVariant")
                        .WithMany("Favorites")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuyerProfile");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.Order", b =>
                {
                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.BuyerProfile", "BuyerProfile")
                        .WithMany("Orders")
                        .HasForeignKey("BuyerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.Receipt", "Receipt")
                        .WithOne("Order")
                        .HasForeignKey("ShahBuyerFeaturesApi.Core.Models.Order", "ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("BuyerProfile");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.OrderItem", b =>
                {
                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.ProductVariant", "ProductVariant")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.OrderPayment", b =>
                {
                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.BuyerProfile", "BuyerProfile")
                        .WithMany("OrderPayments")
                        .HasForeignKey("BuyerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.Order", "Order")
                        .WithOne("OrderPayment")
                        .HasForeignKey("ShahBuyerFeaturesApi.Core.Models.OrderPayment", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BuyerProfile");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.Product", b =>
                {
                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.StoreInfo", "StoreInfo")
                        .WithMany("Products")
                        .HasForeignKey("StoreInfoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("StoreInfo");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.ProductAttribute", b =>
                {
                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.Category", "Category")
                        .WithMany("ProductAttributes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.ProductAttributeValue", b =>
                {
                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.ProductAttribute", "ProductAttribute")
                        .WithMany("AttributeValues")
                        .HasForeignKey("ProductAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductAttribute");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.ProductVariant", b =>
                {
                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.Product", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.ProductVariantAttributeValue", b =>
                {
                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.ProductAttributeValue", "ProductAttributeValue")
                        .WithMany("ProductVariantValues")
                        .HasForeignKey("ProductAttributeValueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.ProductVariant", "ProductVariant")
                        .WithMany("ProductVariantAttributeValues")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductAttributeValue");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.ProductVariantImage", b =>
                {
                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.ProductVariant", "ProductVariant")
                        .WithMany("Images")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.Review", b =>
                {
                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.BuyerProfile", "BuyerProfile")
                        .WithMany("Reviews")
                        .HasForeignKey("BuyerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.ProductVariant", "ProductVariant")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuyerProfile");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.SellerProfile", b =>
                {
                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.User", "User")
                        .WithOne("SellerProfile")
                        .HasForeignKey("ShahBuyerFeaturesApi.Core.Models.SellerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.SellerTaxInfo", b =>
                {
                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.SellerProfile", "SellerProfile")
                        .WithOne("SellerTaxInfo")
                        .HasForeignKey("ShahBuyerFeaturesApi.Core.Models.SellerTaxInfo", "SellerProfileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.Tax", "Tax")
                        .WithMany("SellerTaxInfos")
                        .HasForeignKey("TaxId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SellerProfile");

                    b.Navigation("Tax");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.StoreInfo", b =>
                {
                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.Address", "Address")
                        .WithOne("StoreInfo")
                        .HasForeignKey("ShahBuyerFeaturesApi.Core.Models.StoreInfo", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.Category", "Category")
                        .WithMany("StoreInfos")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.SellerProfile", "SellerProfile")
                        .WithOne("StoreInfo")
                        .HasForeignKey("ShahBuyerFeaturesApi.Core.Models.StoreInfo", "SellerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Category");

                    b.Navigation("SellerProfile");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.User", b =>
                {
                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.CountryCode", "CountryCitizenship")
                        .WithMany("Users")
                        .HasForeignKey("CountryCitizenshipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CountryCitizenship");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.Warehouse", b =>
                {
                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.Address", "Address")
                        .WithOne("Warehouse")
                        .HasForeignKey("ShahBuyerFeaturesApi.Core.Models.Warehouse", "AddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Address");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.WarehouseOrder", b =>
                {
                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.Order", "Order")
                        .WithOne("WarehouseOrder")
                        .HasForeignKey("ShahBuyerFeaturesApi.Core.Models.WarehouseOrder", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShahBuyerFeaturesApi.Core.Models.Warehouse", "Warehouse")
                        .WithMany("WarehouseOrder")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.Address", b =>
                {
                    b.Navigation("BuyerProfile");

                    b.Navigation("StoreInfo");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.BuyerProfile", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Favorites");

                    b.Navigation("OrderPayments");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.Category", b =>
                {
                    b.Navigation("ProductAttributes");

                    b.Navigation("Products");

                    b.Navigation("StoreInfos");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.CountryCode", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("OrderPayment");

                    b.Navigation("WarehouseOrder");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.Product", b =>
                {
                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.ProductAttribute", b =>
                {
                    b.Navigation("AttributeValues");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.ProductAttributeValue", b =>
                {
                    b.Navigation("ProductVariantValues");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.ProductVariant", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Favorites");

                    b.Navigation("Images");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductVariantAttributeValues");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.Receipt", b =>
                {
                    b.Navigation("Order")
                        .IsRequired();
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.SellerProfile", b =>
                {
                    b.Navigation("SellerTaxInfo");

                    b.Navigation("StoreInfo");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.StoreInfo", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.Tax", b =>
                {
                    b.Navigation("SellerTaxInfos");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.User", b =>
                {
                    b.Navigation("AdminProfile");

                    b.Navigation("BuyerProfile");

                    b.Navigation("SellerProfile");
                });

            modelBuilder.Entity("ShahBuyerFeaturesApi.Core.Models.Warehouse", b =>
                {
                    b.Navigation("WarehouseOrder");
                });
#pragma warning restore 612, 618
        }
    }
}
